apiVersion: v1
kind: Secret
metadata:
  name: rhdh-secrets
type: Opaque
stringData:
  RHDH_BASE_URL: $RHDH_BASE_URL
  KEYCLOAK_BASE_URL: $KEYCLOAK_BASE_URL
  KEYCLOAK_METADATA_URL: $KEYCLOAK_METADATA_URL
  KEYCLOAK_LOGIN_REALM: $KEYCLOAK_LOGIN_REALM
  KEYCLOAK_REALM: $KEYCLOAK_REALM
  KEYCLOAK_CLIENT_ID: $KEYCLOAK_CLIENT_ID
  KEYCLOAK_CLIENT_SECRET: $KEYCLOAK_CLIENT_SECRET