apiVersion: v1
kind: Secret
metadata:
  name: rhdh-secrets
type: Opaque
stringData:
  RHDH_BASE_URL: $RHDH_BASE_URL
  GITHUB_OAUTH_APP_SECRET: $GITHUB_OAUTH_APP_SECRET
  GITHUB_OAUTH_APP_ID: $GITHUB_OAUTH_APP_ID